# ========= Recording Settings =========
save_path: "recordings" # output directory
default_device: "" # set to "devicename" to use a specific device by default

# ======= Transcription Settings =======
model: "large-v3" # check https://github.com/openai/whisper for available models
prompt: "Dies ist eine (schweizer-)deutsche Online-Vorlesung meines Professors. Bitte transkribiere den gesprochenen Inhalt wortgetreu auf Deutsch."
language: "de"
remove_silence: true # if true, will remove silence from recordings
